#!/bin/bash

export QCL_HOST="${QCL_HOST:-server}"
export MINI_HOST="${MINI_HOST:-localhost}"
export LAP_HOST="${LAP_HOST:-lap}"

export QCL_BACKEND_PORT="${QCL_BACKEND_PORT:-18000}"
export LOCAL_BACKEND_HOST="${LOCAL_BACKEND_HOST:-0.0.0.0}"
export LOCAL_BACKEND_PORT="${LOCAL_BACKEND_PORT:-3000}"
export FRP_BIND_PORT="${FRP_BIND_PORT:-7000}"
export FRP_VHOST_HTTP_PORT="${FRP_VHOST_HTTP_PORT:-8080}"
export FRP_DASHBOARD_PORT="${FRP_DASHBOARD_PORT:-7500}"
export MINI_PROXY_PORT="${MINI_PROXY_PORT:-5001}"
export REMOTE_TUNNEL_PORT="${REMOTE_TUNNEL_PORT:-5001}"
export QCL_SSH_TARGET="${QCL_SSH_TARGET:-qcl}"
export MINI_TUNNEL_MODE="${MINI_TUNNEL_MODE:-ssh_reverse}"

export BOARD_FETCH_STRATEGY="${BOARD_FETCH_STRATEGY:-server_unified}"
if [ "$MINI_TUNNEL_MODE" = "ssh_reverse" ]; then
    DEFAULT_QCL_PROXY_BASE_URL="http://127.0.0.1:${REMOTE_TUNNEL_PORT}"
else
    DEFAULT_QCL_PROXY_BASE_URL="http://localhost:${FRP_VHOST_HTTP_PORT}/jira_proxy"
fi
export QCL_PROXY_BASE_URL="${QCL_PROXY_BASE_URL:-$DEFAULT_QCL_PROXY_BASE_URL}"
